module App exposing (..)
import Html exposing (..)
import Browser exposing (..)
import Html.Attributes exposing (..)


-- MODEL

-- MSG


-- UPDATE

-- DEFINING FRAMEWORK7 ATTRIBUTES

-- data panel attribute
dataPanel : String -> Attribute msg 
dataPanel name = 
    attribute "data-panel" name 

-- data popover attribute
dataPopover : String -> Attribute msg 
dataPopover name =
    attribute "data-popover" name

-- data name attribute
dataName : String -> Attribute msg 
dataName name =
    attribute "data-name" name

-- VIEW

view : Html msg
view =
    div [ id "app" ]
        [ div [ class "statusbar" ]
            []
        , div [ class "appbar" ]
            [ div [ class "appbar-inner" ]
                [ div [ class "left" ]
                    [ a [ href "#", class "button display-flex" ]
                        [ i [ class "f7-icons" ]
                            [ text "world_fill" ]
                        , div []
                            [ text "GPS" ]
                        ]
                    , div [ class "searchbar searchbar-inline" ]
                        [ input [ type_ "text", placeholder "Search app" ]
                            []
                        , i [ class "searchbar-icon" ]
                            []
                        , div [ class "input-clear-button" ]
                            []
                        ]
                    ]
                , div [ class "right" ]
                    [ a [ href "#", class "link popover-open", dataPopover ".popover-links" ]
                        [ i [ class "f7-icons" ]
                            [ text "person_round_fill" ]
                        ]
                    ]
                ]
            ]
        , div [ class "popover popover-links" ]
            [ div [ class "popover-inner" ]
                [ div [ class "list" ]
                    [ ul []
                        [ li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "User Profile" ]
                            ]
                        , li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "Repositories" ]
                            ]
                        , li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "Projects" ]
                            ]
                        , li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "Help" ]
                            ]
                        , li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "Settings" ]
                            ]
                        , li []
                            [ a [ class "list-button item-link", href "#" ]
                                [ text "Sign Out" ]
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "views tabs safe-areas" ]
            [ div [ class "toolbar tabbar toolbar-bottom" ]
                [ div [ class "toolbar-inner" ]
                    [ a [ href "#view-home", class "tab-link", title "Home" ]
                        [ i [ class "f7-icons" ]
                            [ text "home_fill" ]
                        ]
                    , a [ href "#view-poi", class "tab-link", title "POI" ]
                        [ i [ class "f7-icons" ]
                            [ text "data_fill" ]
                        ]
                    , a [ href "#view-geofence", class "tab-link", title "Geofence" ]
                        [ i [ class "f7-icons" ]
                            [ text "document_chart_fill" ]
                        ]
                    , a [ href "#view-playback", class "tab-link", title "Playback" ]
                        [ i [ class "f7-icons" ]
                            [ text "play_fill" ]
                        ]
                    , a [ href "#view-alerts", class "tab-link", title "Alert Data" ]
                        [ i [ class "f7-icons" ]
                            [ text "alert_fill" ]
                        ]
                    , a [ href "#view-summary", class "tab-link", title "Summary" ]
                        [ i [ class "f7-icons" ]
                            [ text "info_round_fill" ]
                        ]
                    ]
                ]
            , div [ id "view-home", class "view view-main tab tab-active" ]
                [ div [ class "page", dataName "home" ]
                    [ div [ class "panel panel-left panel-cover" ]
                        [ div [ class "list links-list" ]
                            [ ul []
                                [ li []
                                    [ a [ href "#" ]
                                        [ text "NDB 2045" ]
                                    ]
                                , li []
                                    [ a [ href "#" ]
                                        [ text "WVD 4905" ]
                                    ]
                                , li []
                                    [ a [ href "#" ]
                                        [ text "KBV 2395" ]
                                    ]
                                , li []
                                    [ a [ href "#" ]
                                        [ text "JFL 5719" ]
                                    ]
                                , li []
                                    [ a [ href "#" ]
                                        [ text "BSA 5501" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "fab fab-extended fab-bottom" ]
                        [ a [ href "#", class "panel-open" ]
                            [ i [ class "icon f7-icons" ]
                                [ text "bars" ]
                            , div [ class "fab-text" ]
                                [ text "Car Plate" ]
                            ]
                        ]
                    , div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "HOME" ]
                        ]
                    ]
                ]
            , div [ id "view-poi", class "view tab" ]
                [ div [ class "page" ]
                    [ div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "poi" ]
                        ]
                    ]
                ]
            , div [ id "view-geofence", class "view tab" ]
                [ div [ class "page" ]
                    [ div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "Geofence" ]
                        ]
                    ]
                ]
            , div [ id "view-alerts", class "view tab" ]
                [ div [ class "page" ]
                    [ div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "Alerts" ]
                        ]
                    ]
                ]
            , div [ id "view-summary", class "view tab" ]
                [ div [ class "page" ]
                    [ div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "Summary" ]
                        ]
                    ]
                ]
            , div [ id "view-playback", class "view tab" ]
                [ div [ class "page" ]
                    [ div [ class "page-content" ]
                        [ div [ class "block" ]
                            [ text "Playback" ]
                        ]
                    ]
                ]
            ]
        ]

-- MAIN

main =
    view